//package clientFTP;
//
//import java.awt.EventQueue;
//
//import java.awt.BorderLayout;
//import java.awt.Component;
//import java.awt.Dimension;
//import java.awt.event.MouseAdapter;
//import java.awt.event.MouseEvent;
//import java.awt.event.MouseListener;
//import java.awt.event.WindowEvent;
//import java.awt.event.WindowListener;
//import java.io.File;
//
//import javax.swing.DefaultListModel;
//import javax.swing.DropMode;
//import javax.swing.JFileChooser;
//import javax.swing.JList;
//import javax.swing.JOptionPane;
//import javax.swing.JScrollPane;
//import javax.swing.ListSelectionModel;
//import javax.swing.border.EmptyBorder;
//import javax.swing.JFrame;
//
//public class ClientFTPView extends javax.swing.JFrame implements WindowListener{
//
//	private JFrame frame;
//	/*
//	 * To change this license header, choose License Headers in Project Properties.
//	 * To change this template file, choose Tools | Templates
//	 * and open the template in the editor.
//	 */
//
//
//	/**
//	 *
//	 * @author ja
//	 */
//
//	    /**
//	     * Creates new form NewJFrame
//	     */
//	    public ClientFTPView() {
//	        initComponents();
//	    }
//
//	    /**
//	     * This method is called from within the constructor to initialize the form.
//	     * WARNING: Do NOT modify this code. The content of this method is always
//	     * regenerated by the Form Editor.
//	     */
//	    @SuppressWarnings("unchecked")
//	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//	    private void initComponents() {
//
//	        jButton5 = new javax.swing.JButton();
//	        jPanel1 = new javax.swing.JPanel();
//	        jLabel2 = new javax.swing.JLabel();
//	        jScrollPane2 = new javax.swing.JScrollPane();
//	        jTextPane2 = new javax.swing.JTextPane();
//	        jLabel4 = new javax.swing.JLabel();
//	        jButton1 = new javax.swing.JButton();
//	        jPasswordField1 = new javax.swing.JPasswordField();
//	        list2 = new java.awt.List();
//	        jPanel3 = new javax.swing.JPanel();
//	        jScrollPane1 = new javax.swing.JScrollPane();
//	        jTextPane1 = new javax.swing.JTextPane();
//	        jPanel4 = new javax.swing.JPanel();
//	        jButton2 = new javax.swing.JButton();
//	        jButton3 = new javax.swing.JButton();
//	        jButton4 = new javax.swing.JButton();
//	        jButton6 = new javax.swing.JButton();
//	        jScrollPane3 = new javax.swing.JScrollPane();
//	        jList1 = new javax.swing.JList();
//
//	        jButton5.setText("jButton5");
//
//	      //  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//	        jLabel2.setText("Login");
//
//	        jScrollPane2.setViewportView(jTextPane2);
//
//	        jLabel4.setText("Has³o");
//
//	        jButton1.setText("Zaloguj");
//
//	        jPasswordField1.setText("jPasswordField1");
//
//	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//	        jPanel1.setLayout(jPanel1Layout);
//	        jPanel1Layout.setHorizontalGroup(
//	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(jPanel1Layout.createSequentialGroup()
//	                .addContainerGap()
//	                .addComponent(jLabel2)
//	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//	                .addComponent(jLabel4)
//	                .addGap(6, 6, 6)
//	                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//	                .addComponent(jButton1)
//	                .addContainerGap(16, Short.MAX_VALUE))
//	        );
//	        jPanel1Layout.setVerticalGroup(
//	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(jPanel1Layout.createSequentialGroup()
//	                .addContainerGap()
//	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//	                    .addComponent(jPasswordField1)
//	                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
//	                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	        );
//
//	        list2.addActionListener(new java.awt.event.ActionListener() {
//	            public void actionPerformed(java.awt.event.ActionEvent evt) {
//	                list2ActionPerformed(evt);
//	            }
//	        });
//
//	        jScrollPane1.setViewportView(jTextPane1);
//
//	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//	        jPanel3.setLayout(jPanel3Layout);
//	        jPanel3Layout.setHorizontalGroup(
//	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addComponent(jScrollPane1)
//	        );
//	        jPanel3Layout.setVerticalGroup(
//	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
//	        );
//
//	        jButton2.setText("GET");
//	        jButton2.addActionListener(new java.awt.event.ActionListener() {
//	            public void actionPerformed(java.awt.event.ActionEvent evt) {
//	                jButton2ActionPerformed(evt);
//	            }
//	        });
//
//	        jButton3.setText("PUT");
//
//	        jButton4.setText("DIR");
//
//	        jButton6.setText("PWD");
//	        jButton6.addActionListener(new java.awt.event.ActionListener() {
//	            public void actionPerformed(java.awt.event.ActionEvent evt) {
//	                jButton6ActionPerformed(evt);
//	            }
//	        });
//
//	        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//	        jPanel4.setLayout(jPanel4Layout);
//	        jPanel4Layout.setHorizontalGroup(
//	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(jPanel4Layout.createSequentialGroup()
//	                .addGap(27, 27, 27)
//	                .addComponent(jButton2)
//	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	                .addComponent(jButton3)
//	                .addGap(27, 27, 27)
//	                .addComponent(jButton4)
//	                .addGap(29, 29, 29)
//	                .addComponent(jButton6)
//	                .addGap(23, 23, 23))
//	        );
//	        jPanel4Layout.setVerticalGroup(
//	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(jPanel4Layout.createSequentialGroup()
//	                .addContainerGap()
//	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//	                    .addComponent(jButton2)
//	                    .addComponent(jButton3)
//	                    .addComponent(jButton4)
//	                    .addComponent(jButton6))
//	                .addContainerGap(14, Short.MAX_VALUE))
//	        );
//
//	        jList1.setModel(new javax.swing.AbstractListModel() {
//	            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//	            public int getSize() { return strings.length; }
//	            public Object getElementAt(int i) { return strings[i]; }
//	        });
//	        jScrollPane3.setViewportView(jList1);
//
//	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//	        getContentPane().setLayout(layout);
//	        layout.setHorizontalGroup(
//	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//	                .addContainerGap()
//	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//	                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	                    .addGroup(layout.createSequentialGroup()
//	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//	                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
//	                        .addGap(19, 19, 19)
//	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//	                            .addGroup(layout.createSequentialGroup()
//	                                .addGap(0, 0, Short.MAX_VALUE)
//	                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
//	                .addContainerGap())
//	        );
//	        layout.setVerticalGroup(
//	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	            .addGroup(layout.createSequentialGroup()
//	                .addContainerGap()
//	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//	                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//	                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//	                    .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
//	                    .addComponent(jScrollPane3))
//	                .addGap(18, 18, 18)
//	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//	        );
//
//	        pack();
//	    }// </editor-fold>                        
//
//	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//	        // TODO add your handling code here:
//	    }                                        
//
//	    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//	        // TODO add your handling code here:
//	    }                                        
//
//	    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
//	        // TODO add your handling code here:
//	    }                                     
//
//	    /**
//	     * @param args the command line arguments
//	     */
//	    public static void main(String args[]) {
//	        /* Set the Nimbus look and feel */
//	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//	         */
//	        try {
//	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//	                if ("Nimbus".equals(info.getName())) {
//	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//	                    break;
//	                }
//	            }
//	        } catch (ClassNotFoundException ex) {
//	            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	        } catch (InstantiationException ex) {
//	            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	        } catch (IllegalAccessException ex) {
//	            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//	            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	        }
//	        //</editor-fold>
//
//	        /* Create and display the form */
//	        java.awt.EventQueue.invokeLater(new Runnable() {
//	            public void run() {
//	                new ClientFTPView().setVisible(true);
//	            }
//	        });
//	    }
//
//	    // Variables declaration - do not modify                     
//	    private javax.swing.JButton jButton1;
//	    private javax.swing.JButton jButton2;
//	    private javax.swing.JButton jButton3;
//	    private javax.swing.JButton jButton4;
//	    private javax.swing.JButton jButton5;
//	    private javax.swing.JButton jButton6;
//	    private javax.swing.JLabel jLabel2;
//	    private javax.swing.JLabel jLabel4;
//	    private javax.swing.JList jList1;
//	    private javax.swing.JPanel jPanel1;
//	    private javax.swing.JPanel jPanel3;
//	    private javax.swing.JPanel jPanel4;
//	    private javax.swing.JPasswordField jPasswordField1;
//	    private javax.swing.JScrollPane jScrollPane1;
//	    private javax.swing.JScrollPane jScrollPane2;
//	    private javax.swing.JScrollPane jScrollPane3;
//	    private javax.swing.JTextPane jTextPane1;
//	    private javax.swing.JTextPane jTextPane2;
//	    private java.awt.List list2;
//	    // End of variables declaration                   
//
//
//		@Override
//		public void windowOpened(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowClosing(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowClosed(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowIconified(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowDeiconified(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowActivated(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//
//		@Override
//		public void windowDeactivated(WindowEvent e) {
//			// TODO Auto-generated method stub
//			
//		}
//	
//
//	/**
//	 * Launch the application.
//	 */
//
//
//}
//	
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientFTP;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;

import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

import java.awt.Font;
/**
 *
 * @author ja
 */
public class ClientFTPView extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form ClientFTPView
     */
	private static ClientFTPController controller;
	
    public ClientFTPView(ClientFTPController controller) {
    	this.controller = controller;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelGlowny = new javax.swing.JPanel();
        panelLogowania = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        loginTekst = new javax.swing.JTextField();
        haslo = new javax.swing.JLabel();
        hasloTekst = new javax.swing.JPasswordField();
        przyciskZaloguj = new javax.swing.JButton();
        panelOpcje = new javax.swing.JPanel();
        pGet = new javax.swing.JButton();
        pPUT = new javax.swing.JButton();
        pDIR = new javax.swing.JButton();
        pPWD = new javax.swing.JButton();
        //listaFolderySerwer = new javax.swing.JList<String>();
        //fileList = new javax.swing.JList();
        oknoKonsola = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();//wyswietla komendy
        //jTextArea1 = new javax.swing.JTextArea();
        wpisKomendy = new javax.swing.JPanel();
        tekstKomenda = new javax.swing.JTextField();
        pWyslij = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ListTransferHandler arrayListHandler =
                new ListTransferHandler(controller);
        serwerFoldery = new javax.swing.JScrollPane();//jscrollpane2
        listaFolderySerwer = new javax.swing.JList();
        listaFolderySerwer.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listaFolderySerwer.setTransferHandler(arrayListHandler);
        listaFolderySerwer.setCellRenderer(new FileRenderer1());
        plikiTwojKomp = new javax.swing.JScrollPane();//suwakfolderyklient

        
        File f = new File(controller.getPwd());
        File parentF=f.getParentFile();
        File[] lista=f.listFiles(new TextFileFilter());
        File[] newList=new File[lista.length+1];
        for(int i=0;i<lista.length;i++){
     	   newList[i]=lista[i];
        }
        newList[lista.length]=parentF;
        
        fileList = new JList(newList);
        fileList.setDragEnabled(true);
        fileList.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        fileList.setTransferHandler(arrayListHandler);
        
        fileList.setCellRenderer(new FileRenderer(controller));
        fileList.setVisibleRowCount(35);
        //fileList.setCellRenderer(new FileRenderer(controller));
        MouseListener mouseListener = new MouseAdapter() {
    	    public void mouseReleased(MouseEvent e) {
    	      String item =  listaFolderySerwer.getSelectedValue();
    	       String [] lista=item.split("\\s+");
    	    	if(lista.length>1&&lista[1].equals("directory")){
    	    	   controller.cwd(lista[0]); 
    	       }
      	    }
    	   
    	    
    	};
    	
   	 	listaFolderySerwer.addMouseListener(mouseListener);
   	 MouseListener mouseListener1 = new MouseAdapter() {
    	    public void mouseReleased(MouseEvent e) {
    	        
    	   
    	    	File file = (File) fileList.getSelectedValue();
    	    	if(file.isDirectory()) {
    	    		controller.setPwd(file.getPath());
    	    		File[] all=file.listFiles();
    	    		DefaultListModel  model = new DefaultListModel();
    	    	fileList.setModel(model);
        
               // ;
    	    		for(int i=0;i<all.length;i++){
    	    			model.addElement(all[i]);
    	    		}
    	    	
    	    		model.addElement(file.getParentFile());
    	
    	    	}
       
    	       }
 
    	};
    
 	fileList.addMouseListener(mouseListener1);
    addWindowListener(this);

        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login.setText("Login");

        loginTekst.setText("anonymous");
        loginTekst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTekstActionPerformed(evt);
            }
        });

        haslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        haslo.setText("Haslo");

        hasloTekst.setText("         ");

        przyciskZaloguj.setText("Zaloguj");
        przyciskZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskZalogujActionPerformed(evt);
            }
           
        });
       

        javax.swing.GroupLayout panelLogowaniaLayout = new javax.swing.GroupLayout(panelLogowania);
        panelLogowania.setLayout(panelLogowaniaLayout);
        panelLogowaniaLayout.setHorizontalGroup(
            panelLogowaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogowaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTekst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasloTekst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(przyciskZaloguj)
                .addContainerGap())
        );
        panelLogowaniaLayout.setVerticalGroup(
            panelLogowaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogowaniaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelLogowaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasloTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(przyciskZaloguj))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        consolePanel = new ConsolePanel();
        controller.setConsolePanel(consolePanel);
        oknoKonsola.add(consolePanel);
        
        pGet.setText("GET");
        pGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGetActionPerformed(evt);
            }
        });

        pPUT.setText("PUT");
        pPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPUTActionPerformed(evt);
            }
        });

        pDIR.setText("DIR");
        pDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDIRActionPerformed(evt);
            }
        });

        pPWD.setText("PWD");
        pPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPWDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcjeLayout = new javax.swing.GroupLayout(panelOpcje);
        panelOpcjeLayout.setHorizontalGroup(
        	panelOpcjeLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panelOpcjeLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pGet, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(pPUT, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(pDIR, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(pPWD, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        			.addGap(19))
        );
        panelOpcjeLayout.setVerticalGroup(
        	panelOpcjeLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panelOpcjeLayout.createSequentialGroup()
        			.addContainerGap(32, Short.MAX_VALUE)
        			.addGroup(panelOpcjeLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(pPWD)
        				.addComponent(pDIR)
        				.addComponent(pPUT)
        				.addComponent(pGet))
        			.addGap(23))
        );
        panelOpcje.setLayout(panelOpcjeLayout);

        listaFolderySerwer.setModel(new javax.swing.AbstractListModel() {
            String[] strings = controller.getList();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        serwerFoldery.setViewportView(listaFolderySerwer);

//        fileList.setModel(new javax.swing.AbstractListModel() {
//            String[] strings = controller.;
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        plikiTwojKomp.setViewportView(fileList);

//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(consolePanel);
        tekstKomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstKomendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oknoKonsolaLayout = new javax.swing.GroupLayout(oknoKonsola);
        oknoKonsola.setLayout(oknoKonsolaLayout);
        oknoKonsolaLayout.setHorizontalGroup(
            oknoKonsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                );
        oknoKonsolaLayout.setVerticalGroup(
            oknoKonsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        tekstKomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstKomendaActionPerformed(evt);
            }
        });

        pWyslij.setText("Wyslij");
        
        JLabel lblWprowadzKomend = new JLabel("Wprowadz komend\u0119");
        lblWprowadzKomend.setFont(new Font("Tahoma", Font.PLAIN, 14));

        javax.swing.GroupLayout wpisKomendyLayout = new javax.swing.GroupLayout(wpisKomendy);
        wpisKomendyLayout.setHorizontalGroup(
        	wpisKomendyLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(wpisKomendyLayout.createSequentialGroup()
        			.addGroup(wpisKomendyLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(wpisKomendyLayout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(tekstKomenda, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE))
        				.addGroup(wpisKomendyLayout.createSequentialGroup()
        					.addGap(63)
        					.addComponent(lblWprowadzKomend))
        				.addGroup(wpisKomendyLayout.createSequentialGroup()
        					.addGap(97)
        					.addComponent(pWyslij)))
        			.addContainerGap(22, Short.MAX_VALUE))
        );
        wpisKomendyLayout.setVerticalGroup(
        	wpisKomendyLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, wpisKomendyLayout.createSequentialGroup()
        			.addContainerGap(15, Short.MAX_VALUE)
        			.addComponent(lblWprowadzKomend)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(tekstKomenda, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(pWyslij)
        			.addContainerGap())
        );
        wpisKomendy.setLayout(wpisKomendyLayout);

        javax.swing.GroupLayout panelGlownyLayout = new javax.swing.GroupLayout(panelGlowny);
        panelGlownyLayout.setHorizontalGroup(
        	panelGlownyLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelGlownyLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(panelGlownyLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(panelGlownyLayout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(wpisKomendy, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
        					.addComponent(oknoKonsola, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panelGlownyLayout.createSequentialGroup()
        					.addComponent(panelLogowania, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(panelOpcje, GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        				.addGroup(panelGlownyLayout.createSequentialGroup()
        					.addComponent(plikiTwojKomp, GroupLayout.PREFERRED_SIZE, 346, GroupLayout.PREFERRED_SIZE)
        					.addGap(52)
        					.addComponent(serwerFoldery, GroupLayout.PREFERRED_SIZE, 379, GroupLayout.PREFERRED_SIZE)
        					.addGap(8)))
        			.addGap(30))
        );
        panelGlownyLayout.setVerticalGroup(
        	panelGlownyLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelGlownyLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(panelGlownyLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(panelOpcje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(panelLogowania, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panelGlownyLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(serwerFoldery, GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        				.addComponent(plikiTwojKomp, GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(panelGlownyLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(oknoKonsola, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(wpisKomendy, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        			.addGap(20))
        );
        panelGlowny.setLayout(panelGlownyLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void loginTekstActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void przyciskZalogujActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	                                           
             if(loginTekst.getText().isEmpty()){
           	  JOptionPane.showMessageDialog(this, "Podaj login.",
       					"Uwaga", JOptionPane.WARNING_MESSAGE);
             }
             else{
           	  controller.loginUser(loginTekst.getText(),hasloTekst.getText());	  
             }
          
    }                                               

    private void pGetActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	OknoDir dir=new OknoDir(controller,"GET");
 	   dir.setVisible(true);
    }                                    

    private void pPUTActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	OknoDir dir=new OknoDir(controller,"PUT");
 	   dir.setVisible(true);
    }                                    

    private void pDIRActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	 OknoDir dir=new OknoDir(controller,"DIR");
  	   dir.setVisible(true);
    }                                    

    private void pPWDActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	controller.pwd();
    }                                    

    private void tekstKomendaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    public void setListModel(){
 	   listaFolderySerwer.setModel(new javax.swing.AbstractListModel<String>() {
            /**
 		 * 
 		 */
 		private static final long serialVersionUID = 1L;
 		String[] strings = controller.getList();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
 	
 	 revalidate();
 	   
    }
    public void  restartLocalFilesList(){
 	   
 	   File f = new File(controller.getPwd());
        File parentF=f.getParentFile();
        
        File[] lista=f.listFiles(new TextFileFilter());
        File[] newList=new File[lista.length+1];
        for(int i=0;i<lista.length;i++){
     	   newList[i]=lista[i];
        }
        newList[lista.length]=parentF;
        
        DefaultListModel  model = new DefaultListModel();
 	    	fileList.setModel(model);
   
          // ;
 	    		for(int i=0;i<newList.length;i++){
 	    			model.addElement(newList[i]);
 	    		}
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClientFTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClientFTPView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JList fileList;
    private javax.swing.JLabel haslo;
    private javax.swing.JPasswordField hasloTekst;
    private javax.swing.JScrollPane jScrollPane4;//okno konsola, wyswietla
    //private javax.swing.JTextArea jTextArea1;//wypisywana komenda
    private javax.swing.JList<String> listaFolderySerwer;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginTekst;
    private javax.swing.JPanel oknoKonsola;
    private javax.swing.JButton pDIR;
    private javax.swing.JButton pGet;
    private javax.swing.JButton pPUT;
    private javax.swing.JButton pPWD;
    private javax.swing.JButton pWyslij;
    private javax.swing.JPanel panelGlowny;
    private javax.swing.JPanel panelLogowania;
    private javax.swing.JPanel panelOpcje;
    private javax.swing.JScrollPane plikiTwojKomp;
    private javax.swing.JButton przyciskZaloguj;
    private javax.swing.JScrollPane serwerFoldery;
    private javax.swing.JTextField tekstKomenda;
    private javax.swing.JPanel wpisKomendy;
    private ConsolePanel consolePanel;
    private javax.swing.JLabel jLabel1;//tekst "wprowadz komende"
    // End of variables declaration                   
	@Override
	public void windowOpened(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowClosing(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	
	
	public void windowClosed(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowIconified(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeiconified(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowActivated(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeactivated(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}
}