package clientFTP;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

public class OknoAbor extends javax.swing.JFrame implements WindowListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form oknoAbor
	 */
	private ClientFTPController controller;

	/**
	 * Creates new form IPPanel
	 */
	private String option;
	private String tekst;

	public OknoAbor(ClientFTPController controller, String option, String tekst) {
		this.controller = controller;
		this.tekst = tekst;
		this.option = option;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		etykietaInfo = new javax.swing.JLabel();
		przyciskAbor = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		etykietaInfo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
		etykietaInfo.setText(tekst);

		przyciskAbor.setText(option);
		przyciskAbor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				przyciskAborActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap(41, Short.MAX_VALUE)
								.addComponent(etykietaInfo,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										184,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(37, 37, 37))
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addGap(87, 87, 87)
								.addComponent(przyciskAbor)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(
												etykietaInfo,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(przyciskAbor)
										.addContainerGap(19, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void przyciskAborActionPerformed(java.awt.event.ActionEvent evt) {
		if (option.equals("Przerwij")) {
			controller.abor();
			dispose();
		}
		
		
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel etykietaInfo;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton przyciskAbor;

	// End of variables declaration

	@Override
	public void windowActivated(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowClosed(WindowEvent e) {
		// TODO Auto-generated method stub
		if (option.equals("Przerwij")) {
			controller.abor();
		}
		
	
	}

	@Override
	public void windowClosing(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowDeactivated(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowDeiconified(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowIconified(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowOpened(WindowEvent e) {
		// TODO Auto-generated method stub

	}
}